### ISSUE TITLE
Exception java.lang.NoClassDefFoundError when using MQTT tests

### ISSUE THREAD

**Issue by matheus-fonseca** [tuanhiep/mqtt-jmeter-plugin#12]
I'm trying to make a MQTT test (pub/sub) but Jmeter gives me this Exception:

```
2015/05/29 11:21:33 ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.NoClassDefFoundError: org/fusesource/mqtt/client/Callback
    at org.apache.jmeter.protocol.mqtt.sampler.SubscriberSampler.threadStarted(SubscriberSampler.java:221)
    at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:610)
    at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:998)
    at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:980)
    at org.apache.jmeter.threads.JMeterThread.threadStarted(JMeterThread.java:579)
    at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:567)
    at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.fusesource.mqtt.client.Callback
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 8 more

2015/05/29 11:21:33 INFO  - jmeter.threads.JMeterThread: Thread finished: Grupo de Usuários 1-1 
2015/05/29 11:21:33 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: org/fusesource/mqtt/client/Listener
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at org.apache.jmeter.protocol.mqtt.sampler.SubscriberSampler.threadFinished(SubscriberSampler.java:282)
    at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:612)
    at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:998)
    at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:980)
    at org.apache.jmeter.threads.JMeterThread.threadFinished(JMeterThread.java:584)
    at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:315)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.fusesource.mqtt.client.Listener
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 18 more

2015/05/29 11:21:33 INFO  - jmeter.engine.StandardJMeterEngine: Notifying test listeners of end of test 
2015/05/29 11:21:33 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: org/apache/jmeter/protocol/mqtt/client/ListenerforSubscribe
    at org.apache.jmeter.protocol.mqtt.sampler.SubscriberSampler.testEnded(SubscriberSampler.java:179)
    at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:226)
    at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:448)
    at java.lang.Thread.run(Thread.java:745)
```

I followed your installation instructions at README.

**Comment by hemikak** [comment]
This is because fusesource library files are not getting included in the mqtt plugin jar.
Add the pom file fix mentioned in https://github.com/tuanhiep/mqtt-jmeter/pull/1/files and see.

**Comment by andreibosco** [comment]
I've tried using the fixed pom file and now I can't build the project:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.304 s
[INFO] Finished at: 2015-06-13T14:15:36-03:00
[INFO] Final Memory: 18M/45M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.0:shade (default) on project mqtt-jmeter: Execution default of goal org.apache.maven.plugins:maven-shade-plugin:2.0:shade failed: A required class was missing while executing org.apache.maven.plugins:maven-shade-plugin:2.0:shade: org/sonatype/aether/version/VersionConstraint
[ERROR] -----------------------------------------------------

**Comment by hemikak** [comment]
Hi @andreibosco , 

What is the maven version you are using ?
I am using 3.0.5.

**Comment by andreibosco** [comment]
I'm using 3.3.3. I've just changed maven-shade-plugin from 2.0 to 2.1 and now it builds fine.

**Comment by firesh-bakhda** [comment]
You will need to build JMeter with dependencies. Add the following to the POM.xml 

```
        <plugin>
            <artifactId>maven-assembly-plugin</artifactId>

            <configuration>
                <descriptorRefs>
                    <descriptorRef>jar-with-dependencies</descriptorRef>
                </descriptorRefs>
            </configuration>

            <executions>
                <execution>
                    <id>make-assembly</id>
                    <phase>package</phase>
                    <goals>
                        <goal>single</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
```

Add this to the <plugins> tag. 

Secondly, make sure your JMeter version complies to the JMeter version you are using. 
        <jmeter-version>2.13</jmeter-version>

Third, change the mqtt-client library version to 1.10 instead of 1.4 
(Thou i think both are working as what i tried)

```
    <dependency>
      <groupId>org.fusesource.mqtt-client</groupId>
      <artifactId>mqtt-client</artifactId>
      <version>1.10</version>
    </dependency>
```

By doing this you eliminate all the FutureListener exceptions, input string "" errors and so on. 
1) Publisher: Input string "" errors are becoz of Suffix Length is empty on the UI, so make sure you have value

2) Subscriber: Input string "" errors are becoz of Timeout is empty, make sure put a timeout there

Full Sample pom.xml



<project
        xmlns="http://maven.apache.org/POM/4.0.0" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

```
<modelVersion>4.0.0</modelVersion>

<groupId>fr.liglab.erods.jmeter.mqtt</groupId>
<artifactId>mqtt-jmeter</artifactId>
<version>0.0.1-SNAPSHOT</version>
<name>Apache JMeter :: MQTT Injector</name>
<description>MQTT Injector for Apache JMeter</description>

<properties>
    <jmeter-version>2.13</jmeter-version>
</properties>

<dependencies>


    <dependency>
        <groupId>org.apache.jmeter</groupId>
        <artifactId>ApacheJMeter_core</artifactId>
        <version>${jmeter-version}</version>
        <scope>provided</scope>
    </dependency>

    <dependency>
        <groupId>org.apache.jmeter</groupId>
        <artifactId>ApacheJMeter_java</artifactId>
        <version>${jmeter-version}</version>
        <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.fusesource.mqtt-client</groupId>
      <artifactId>mqtt-client</artifactId>
      <version>1.10</version>
    </dependency>

</dependencies>

<build>
    <finalName>${project.artifactId}</finalName>
    <defaultGoal>install</defaultGoal>
    <plugins>

        <plugin>
            <artifactId>maven-assembly-plugin</artifactId>

            <configuration>
                <descriptorRefs>
                    <descriptorRef>jar-with-dependencies</descriptorRef>
                </descriptorRefs>
            </configuration>

            <executions>
                <execution>
                    <id>make-assembly</id>
                    <phase>package</phase>
                    <goals>
                        <goal>single</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>

        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>2.5.1</version>
            <configuration>
                <source>1.6</source>
                <target>1.6</target>
            </configuration>
        </plugin>

    </plugins>
</build>
```

</project>

Current remaining issues that i still see : 

1) Publisher : Client ID value on UI is not retained.
2) Publisher & Subscriber : Suffix Length Values are not retained
3) Subscriber : Keeps saying Received 0 messages thou there is something published.

@tuanhiep - Do have a look and see if i make any sense to ease your understanding.

**Comment by gBarrerasSanz** [comment]
I'm getting the same exception while trying to execute the subscriber. Here is the stack trace:
````
2015/09/16 04:17:02 INFO  - jmeter.util.BSFTestElement: Registering JMeter version of JavaScript engine as work-round for BSF-22 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [critical_section_controller_title] 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [critical_section_controller_title] 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [critical_section_controller_label] 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [critical_section_controller_title] 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [critical_section_controller_title] 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [regex_src_hdrs_req] 
2015/09/16 04:17:03 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Cannot find .className property for htmlParser, using default 
2015/09/16 04:17:03 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/html is  
2015/09/16 04:17:03 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xhtml+xml is  
2015/09/16 04:17:03 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xml is  
2015/09/16 04:17:03 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/xml is  
2015/09/16 04:17:03 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser 
2015/09/16 04:17:03 INFO  - jmeter.gui.util.MenuFactory: Skipping org.apache.jmeter.protocol.http.control.gui.WebServiceSamplerGui 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [use_system_dns_resolver] 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [use_custom_dns_resolver] 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_hostname_or_ip] 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [clear_cache_each_iteration] 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_servers] 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:03 INFO  - jmeter.gui.util.MenuFactory: Skipping org.apache.jmeter.protocol.http.modifier.gui.ParamModifierGui 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [encode] 
2015/09/16 04:17:03 INFO  - jorphan.exec.KeyToolUtils: keytool found at 'C:\Program Files\Java\jre1.8.0_60\bin\keytool' 
2015/09/16 04:17:03 INFO  - jmeter.protocol.http.proxy.ProxyControl: HTTP(S) Test Script Recorder SSL Proxy will use keys that support embedded 3rd party resources in file C:\utilities\portableFiles\apache-jmeter-2.13_source\bin\proxyserver.jks 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [notify_child_listeners_fr] 
2015/09/16 04:17:03 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [notify_child_listeners_fr] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jms_expiration] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jms_priority] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jms_expiration] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [jms_priority] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [mail_reader_header_only] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [smtp_server_timeout] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [smtp_server_connection_timeout] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [smtp_server_timeouts_settings] 
2015/09/16 04:17:04 INFO  - jmeter.samplers.SampleResult: Note: Sample TimeStamps are START times 
2015/09/16 04:17:04 INFO  - jmeter.samplers.SampleResult: sampleresult.default.encoding is set to ISO-8859-1 
2015/09/16 04:17:04 INFO  - jmeter.samplers.SampleResult: sampleresult.useNanoTime=true 
2015/09/16 04:17:04 INFO  - jmeter.samplers.SampleResult: sampleresult.nanoThreadSleep=5000 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [aggregate_report_xx_pct1_line] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [aggregate_report_xx_pct2_line] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [aggregate_report_xx_pct3_line] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener_classname] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener_queue_size] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener_paramtable] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [critical_section_controller_title] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [critical_section_controller_title] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [critical_section_controller_title] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [critical_section_controller_title] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [undo] 
2015/09/16 04:17:04 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [redo] 
2015/09/16 04:17:05 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:05 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:05 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [undo] 
2015/09/16 04:17:05 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [redo] 
2015/09/16 04:17:11 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:11 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:11 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [undo] 
2015/09/16 04:17:11 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [redo] 
2015/09/16 04:17:16 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [critical_section_controller_title] 
2015/09/16 04:17:16 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:16 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:16 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [undo] 
2015/09/16 04:17:16 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [redo] 
2015/09/16 04:17:17 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [critical_section_controller_title] 
2015/09/16 04:17:17 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:17 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:17 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [undo] 
2015/09/16 04:17:17 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [redo] 
2015/09/16 04:17:23 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [dns_cache_manager_title] 
2015/09/16 04:17:23 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [backend_listener] 
2015/09/16 04:17:23 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [critical_section_controller_title] 
2015/09/16 04:17:23 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [undo] 
2015/09/16 04:17:23 WARN  - jmeter.util.JMeterUtils: ERROR! Resource string not found: [redo] 
2015/09/16 04:18:02 INFO  - jmeter.services.FileServer: Default base='C:\utilities\portableFiles\apache-jmeter-2.13_source\bin' 
2015/09/16 04:18:02 INFO  - jmeter.services.FileServer: Set new base='C:\utilities\portableFiles\apache-jmeter-2.13_source\bin' 
2015/09/16 04:18:02 INFO  - jmeter.save.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2 
2015/09/16 04:18:02 INFO  - jmeter.save.SaveService: Using SaveService properties file encoding UTF-8 
2015/09/16 04:18:02 INFO  - jmeter.save.SaveService: Using SaveService properties file version 1656252 
2015/09/16 04:18:02 INFO  - jmeter.save.SaveService: Using SaveService properties version 2.8 
2015/09/16 04:18:02 INFO  - jmeter.save.SaveService: All converter versions present and correct 
2015/09/16 04:18:03 INFO  - jmeter.engine.StandardJMeterEngine: Listeners will be started after enabling running version 
2015/09/16 04:18:03 INFO  - jmeter.engine.StandardJMeterEngine: To revert to the earlier behaviour, define jmeterengine.startlistenerslater=false 
2015/09/16 04:18:03 INFO  - jmeter.engine.StandardJMeterEngine: Running the test! 
2015/09/16 04:18:03 INFO  - jmeter.samplers.SampleEvent: List of sample_variables: [] 
2015/09/16 04:18:03 INFO  - jmeter.samplers.SampleEvent: List of sample_variables: [] 
2015/09/16 04:18:03 INFO  - jmeter.gui.util.JMeterMenuBar: setRunning(true,*local*) 
2015/09/16 04:18:03 INFO  - jmeter.engine.StandardJMeterEngine: Starting ThreadGroup: 1 : Grupo de Hilos 
2015/09/16 04:18:03 INFO  - jmeter.engine.StandardJMeterEngine: Starting 1 threads for group Grupo de Hilos. 
2015/09/16 04:18:03 INFO  - jmeter.engine.StandardJMeterEngine: Thread will continue on error 
2015/09/16 04:18:03 INFO  - jmeter.threads.ThreadGroup: Starting thread group number 1 threads 1 ramp-up 1 perThread 1000.0 delayedStart=false 
2015/09/16 04:18:03 INFO  - jmeter.threads.JMeterThread: jmeterthread.startearlier=true (see jmeter.properties) 
2015/09/16 04:18:03 INFO  - jmeter.threads.JMeterThread: Running PostProcessors in forward order 
2015/09/16 04:18:03 INFO  - jmeter.threads.ThreadGroup: Started thread group number 1 
2015/09/16 04:18:03 INFO  - jmeter.engine.StandardJMeterEngine: All thread groups have been started 
2015/09/16 04:18:03 INFO  - jmeter.threads.JMeterThread: Thread started: Grupo de Hilos 1-1 
2015/09/16 04:18:03 ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.NoClassDefFoundError: org/fusesource/mqtt/client/Callback
	at org.apache.jmeter.protocol.mqtt.sampler.SubscriberSampler.threadStarted(SubscriberSampler.java:221)
	at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:610)
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:998)
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:980)
	at org.apache.jmeter.threads.JMeterThread.threadStarted(JMeterThread.java:579)
	at org.apache.jmeter.threads.JMeterThread.initRun(JMeterThread.java:567)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.fusesource.mqtt.client.Callback
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more

2015/09/16 04:18:03 INFO  - jmeter.threads.JMeterThread: Thread finished: Grupo de Hilos 1-1 
2015/09/16 04:18:03 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: org/fusesource/mqtt/client/Listener
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.apache.jmeter.protocol.mqtt.sampler.SubscriberSampler.threadFinished(SubscriberSampler.java:282)
	at org.apache.jmeter.threads.JMeterThread$ThreadListenerTraverser.addNode(JMeterThread.java:612)
	at org.apache.jorphan.collections.HashTree.traverseInto(HashTree.java:998)
	at org.apache.jorphan.collections.HashTree.traverse(HashTree.java:980)
	at org.apache.jmeter.threads.JMeterThread.threadFinished(JMeterThread.java:584)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:315)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.fusesource.mqtt.client.Listener
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more

2015/09/16 04:18:03 INFO  - jmeter.engine.StandardJMeterEngine: Notifying test listeners of end of test 
2015/09/16 04:18:03 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NoClassDefFoundError: org/apache/jmeter/protocol/mqtt/client/ListenerforSubscribe
	at org.apache.jmeter.protocol.mqtt.sampler.SubscriberSampler.testEnded(SubscriberSampler.java:179)
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:226)
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:448)
	at java.lang.Thread.run(Unknown Source)
````
I think I've followed your instructions properly; i.e.:
 Build this mqtt project (with maven 3.3.3), put the mqtt-jemeter.jar in the folder lib/ext of Jmeter, replace the /org/apache/jmeter/resources/messages.properties  in Jmeter project by  mqtt /ressources/messages.properties in mqtt project, build Jmeter, and finally run Jmeter.
I may misunderstood some step. 

I've also tried to change pom.xml file from mqtt project by the one @firesh-bakhda, but I got the following error:
````
C:\utilities\portableFiles\mqtt-jmeter-master>mvn clean install package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Apache JMeter :: MQTT Injector 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for commons-math3:commons-math3:jar:3.4.1 is missing, no dependency information available
[WARNING] The POM for commons-pool2:commons-pool2:jar:2.3 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.625 s
[INFO] Finished at: 2015-09-16T04:33:25+02:00
[INFO] Final Memory: 10M/162M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project mqtt-jmeter: Could not resolve dependencies for project fr.liglab.erods.jmeter.mqtt:mqtt-jmeter:jar:0.0.1-SNAPSHOT: The following artifacts could not be resol
ved: commons-math3:commons-math3:jar:3.4.1, commons-pool2:commons-pool2:jar:2.3: Failure to find commons-math3:commons-math3:jar:3.4.1 in https://repo.maven.apache.org/maven2 was cached in the local r
epository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
````
Can you help me?

Thank you!
