### ISSUE TITLE
getting NullPointerException error

### ISSUE THREAD

**Issue by andreibosco** [tuanhiep/mqtt-jmeter-plugin#13]
I'm getting the following error when I try to make an MQTT test (either pub or sub):
`2015/06/13 14:26:27 ERROR - jmeter.protocol.java.sampler.AbstractJavaSamplerClient:`

And when I stop the simulation the following error message is shown in the log:

```
2015/06/13 14:29:17 ERROR - jmeter.JMeter: Uncaught exception:  java.lang.NullPointerException
    at org.fusesource.mqtt.client.CallbackConnection$8.onSuccess(CallbackConnection.java:506)
    at org.fusesource.mqtt.client.CallbackConnection$8.onSuccess(CallbackConnection.java:495)
    at org.fusesource.mqtt.client.CallbackConnection.disconnect(CallbackConnection.java:519)
    at org.fusesource.mqtt.client.FutureConnection$3.run(FutureConnection.java:104)
    at org.fusesource.hawtdispatch.internal.SerialDispatchQueue.run(SerialDispatchQueue.java:96)
    at org.fusesource.hawtdispatch.internal.pool.SimpleThread.run(SimpleThread.java:77)
```

Here's a screenshot of the parameters I'm using in Jmeter: https://dl.dropboxusercontent.com/u/546167/jmeter-mqtt-error.PNG

**Comment by firesh-bakhda** [comment]
Refer to the my comment on Issue #12 , a full pom.xml is there
